### ISSUE TITLE
Sometime the plugin need to transfer the `getPhoto()` function

### ISSUE THREAD

**Issue by Desgard** [HackSwjtu/Postime#7]
## User needs

When I visit the login page of SWJTU dean by the URL(http://202.115.67.4/service/login.jsp), I need to click the button `点击获取验证码` to get the verification code. 

To automate it! 💪

![f46e75b6-46e8-4546-bb67-ce5ce7b97595](https://cloud.githubusercontent.com/assets/7804535/24276290/8390a960-1070-11e7-9f2d-e9e20951b0c2.png)

**Comment by lianglanzheng** [comment]
Fixed.

**Comment by Desgard** [comment]
Good job.
